# Default values for ..
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

dashboard:
  replicaCount: 1
  image:
    repository: sprints-dashboard
    pullPolicy: IfNotPresent
    tag: local
  imagePullSecrets: []
  podSecurityContext: {}
  securityContext: {}
  service:
    type: ClusterIP
    port: 80
    targetPort: 8000
  ingress:
    enabled: false
    hosts:
      - host: localhost
        paths:
          - /
    tls: []
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

jira:
  config: {}
  credentials:
    existingSecret: ""

dataCollection:
  enabled: false
  image:
    repository: sprints-dashboard
    pullPolicy: IfNotPresent
    tag: local

mongodb:
  architecture: standalone
  useStatefulSet: true
  initContainers: []
  auth:
    existingSecret: ""
  resources: {}
