{{- if .Values.dataCollection.enabled -}}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: sprints-extract
spec:
  schedule: "00 16 * * FRI"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: sprints-extract
            image: "{{ .Values.dataCollection.image.repository }}:{{ .Values.dataCollection.image.tag }}"
            imagePullPolicy: {{ .Values.dashboard.image.pullPolicy }}
            command: ["python"]
            args: ["cli.py", "extract", "sprints", "latest"]
            volumeMounts:
              - name: config-volume
                mountPath: /opt/code/config_files
            env:
              - name: DB_HOST
                value: {{ include "..fullname" . }}-mongodb
              - name: DB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: {{ required "Must supply an existing mongodb secret" .Values.mongodb.auth.existingSecret }}
                    key: mongodb-root-password
              - name: JIRA_EMAIL
                valueFrom:
                  secretKeyRef:
                    name: {{ required "Must supply an existing jira secret" .Values.jira.credentials.existingSecret }}
                    key: jira-email
              - name: JIRA_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: {{ required "Must supply an existing jira secret" .Values.jira.credentials.existingSecret }}
                    key: access-token
          volumes:
            - name: config-volume
              configMap:
                name: jira-config
          restartPolicy: Never
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: sprints
  name: historic-issues-extract
spec:
  schedule: "15 16 * * FRI"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: historic-issues-extract
            image: "{{ .Values.dataCollection.image.repository }}:{{ .Values.dataCollection.image.tag }}"
            imagePullPolicy: {{ .Values.dashboard.image.pullPolicy }}
            command: ["python"]
            args: ["cli.py", "extract", "issues"]
            volumeMounts:
              - name: config-volume
                mountPath: /opt/code/config_files
            env:
              - name: DB_HOST
                value: {{ include "..fullname" . }}-mongodb
              - name: DB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: {{ required "Must supply an existing mongodb secret" .Values.mongodb.auth.existingSecret }}
                    key: mongodb-root-password
              - name: JIRA_EMAIL
                valueFrom:
                  secretKeyRef:
                    name: {{ required "Must supply an existing jira secret" .Values.jira.credentials.existingSecret }}
                    key: jira-email
              - name: JIRA_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: {{ required "Must supply an existing jira secret" .Values.jira.credentials.existingSecret }}
                    key: access-token
          volumes:
            - name: config-volume
              configMap:
                name: jira-config
          restartPolicy: Never
{{- end}}