apiVersion: apps/v1
kind: Deployment
metadata:
  name: agile-dashboard
  labels:
    name: agile-dashboard
spec:
  replicas: {{ .Values.dashboard.replicaCount }}
  selector:
    matchLabels:
      app: agile-dashboard
  template:
    metadata:
      labels:
        app: agile-dashboard
    spec:
    {{- with .Values.dashboard.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.dashboard.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.dashboard.securityContext | nindent 12 }}
          image: "{{ .Values.dashboard.image.repository }}:{{ .Values.dashboard.image.tag }}"
          imagePullPolicy: {{ .Values.dashboard.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.dashboard.resources | nindent 12 }}
          volumeMounts:
            - name: config-volume
              mountPath: /opt/code/config_files
          env:
            - name: DB_HOST
              value: mongo-mongodb
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ required "Must supply an existing mongodb secret" .Values.mongodb.auth.existingSecret }}
                  key: mongodb-root-password
            # - name: JIRA_EMAIL
            #   valueFrom:
            #     secretKeyRef:
            #       name: {{ required "Must supply an existing jira secret" .Values.jira.credentials.existingSecret }}
            #       key: jira-email
            # - name: JIRA_TOKEN
            #   valueFrom:
            #     secretKeyRef:
            #       name: {{ required "Must supply an existing jira secret" .Values.jira.credentials.existingSecret }}
            #       key: jira-token
      volumes:
        - name: config-volume
          configMap:
            name: jira-config
      {{- with .Values.dashboard.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.dashboard.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.dashboard.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
