{{- if .Values.dashboard.ingress.enabled -}}
{{- $fullName := include "..fullname" . -}}
{{- $svcPort := .Values.dashboard.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: agile-dashboard
  annotations: {{ .Values.dashboard.ingress.annotations }}
spec:
{{- if .Values.dashboard.ingress.tls }}
  tls:
  {{- range .Values.dashboard.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.dashboard.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ . }}
            pathType: Prefix
            backend:
              serviceName: agile-dashboard
              servicePort: {{ $svcPort }}
        {{- end }}
  {{- end }}
{{- end }}
