apiVersion: v1
kind: Service
metadata:
  name: agile-dashboard
  annotations: {{ .Values.dashboard.service.annotations }}
spec:
  type: {{ .Values.dashboard.service.type }}
  ports:
    - port: {{ .Values.dashboard.service.port }}
      targetPort: {{ .Values.dashboard.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: agile-dashboard
